version: 2
jobs:
    build:
        working_directory: ~/contentacms
        docker:
            - image: notnoopci/php:7.1.5-browsers
        steps:
            - checkout
    test_pr_environment:
        working_directory: ~/contentacms
        docker:
            - image: 'php:7.1'
        steps:
            - checkout
            - run:
                name: Install PHP SQLite & GD
                command: |
                    sudo apt-get update -y
                    sudo apt-get install -y libpng-dev libjpeg-dev php7.0-gd php-sqlite3
                    sudo php5enmod gd
                    php -r 'print_r(get_loaded_extensions());'
                    curl -s -f -L -o /tmp/installer.php https://raw.githubusercontent.com/composer/getcomposer.org/da290238de6d63faace0343efbdd5aa9354332c5/web/installer
                    php -r " \
                        \$signature = '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410'; \
                        \$hash = hash('SHA384', file_get_contents('/tmp/installer.php')); \
                        if (!hash_equals(\$signature, \$hash)) { \
                            unlink('/tmp/installer.php'); \
                            echo 'Integrity check failed, installer is either corrupt or worse.' . PHP_EOL; \
                            exit(1); \
                        }"
                    php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}
                    rm /tmp/installer.php
                    composer --ansi --version --no-interaction
            - run: composer run-script install-contenta ~/contenta-env --timeout=0
            - run: |
                export DISPLAY=:99.0
                # Prevent chrome deadlock when running Nightwatch tests.
                # See https://stackoverflow.com/questions/41487659/nightwatch-selenium-socket-hang-up
                export DBUS_SESSION_BUS_ADDRESS=/dev/null
                sh -e /etc/init.d/xvfb start
            - run: |
                sleep 3 # give xvfb some time to start
                composer run-script start-contenta ~/contenta-env --timeout=0
            - run: yarn run nightwatch
    trigger_build:
        working_directory: ~/contentacms
        docker:
            - image: notnoopci/php:7.1.5-browsers
        steps:
            - run: |
                mkdir ~/.ssh
                echo -e "Host *\n  StrictHostKeyChecking no\n  HashKnownHosts no\n  SendEnv LANG LC_*\n" >> ~/.ssh/config
            - run:
                name: Clone demo site repo
                command: git clone git@github.com:contentacms/contenta_jsonapi_demo.git contenta_jsonapi_demo
            - run:
                name: Add and commit trigger
                command: |
                    cd contenta_jsonapi_demo
                    pwd
                    echo -e "  * Profile update -> buildNum=[$CIRCLE_BUILD_NUM]($CIRCLE_BUILD_URL) on [$CIRCLE_PR_REPONAME]($CIRCLE_REPOSITORY_URL)@CIRCLE_SHA1\n" >> DEPLOYS.md
                    cat DEPLOYS.md
                    git config --global user.email "bot@contentacms.org"
                    git config --global user.name "Contenta CMS CI Bot"
                    git status
                    git add DEPLOYS.md
                    git commit -m 'ci(Deploy): Trigger a deploy to the demo site'
                    git push origin master
            - run:
                name: Cleanup
                command: |
                    rm -fr contenta_jsonapi_demo
workflows:
    version: 2
    deploy_demo_site:
        jobs:
            - build
            - trigger_build:
                requires:
                    - build
                filters:
                    branches:
                        only: 8.x-1.x
    run_tests:
        jobs:
            - test_pr_environment
